### ISSUE TITLE
Bigquery integration

### ISSUE THREAD

**Issue by sidPhoenix17** [DrDroidLab/PlayBooks#446]
## What new integration do you require?

*Please describe.*

## Additional context
Add any other context about the new integration here.

#### *Thank you* for your new integration request!

**Comment by vpavankalyan** [comment]
Hey @sidPhoenix17, 
I would like to work on the issue, if it is up for grabs.
can you give me more context on the issue.

**Comment by sidPhoenix17** [comment]
Hi @vpavankalyan , you can go ahead and pick it up.

@dimittal @droid-mohit can you help share exact behaviour here?

**Comment by droid-mohit** [comment]
Hi @vpavankalyan 
There are 3 types of changes to be added in the repo for a new integration-

1. handle connection to bigquery engine via playbooks
2. define and implement changes to execute big query (google sql) and get results in table format on playbooks
3. define assets that can be used in tasks to help create the tasks for bigquery 

You can follow the below PRs in same order to achieve the same

- New connector PR: https://github.com/DrDroidLab/PlayBooks/pull/280
- New Task Source PR: https://github.com/DrDroidLab/PlayBooks/pull/282/files
- Asset manager PR: https://github.com/DrDroidLab/PlayBooks/pull/284

These PRs are a good starting point to plan your changes. Please note there might be some changes added to the repo since the time these PRs were created, so you might have to navigate those. Feel free to reach out on our slack community if you get stuck anywhere. 

You can follow this guide for setting up playbooks on your local - 
https://www.youtube.com/watch?v=OiwgXSncNuo&list=PL-09IrZSH_gJXP4XfosRsMBIcj6iFu4ts&index=11
